version: '3.8'

services:
  backend:
    image: photos_backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    command: poetry run gunicorn photos.wsgi -c ./build/gunicorn.conf.py
    expose:
      - 1337
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_USER=photos
      - DATABASE_PASSWORD=photos
      - DATABASE_NAME=photos
    depends_on:
      - db
      - redis

  nginx:
    image: photos_nginx
    container_name: nginx
    build: ./build/nginx/
    ports:
      - 443:443
    depends_on:
      - backend

  redis:
    extends:
      file: docker-services.yml
      service: redis

  celery:
    extends:
      file: docker-services.yml
      service: celery
    build:
      target: staging
    depends_on:
      - backend
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_USER=photos
      - DATABASE_PASSWORD=photos
      - DATABASE_NAME=photos

  db:
    image: postgres:10.20-alpine
    container_name: db
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
    environment:
      - POSTGRES_USER=photos
      - POSTGRES_PASSWORD=photos
      - POSTGRES_DB=photos

volumes:
  postgres_data_staging:
  static_volume:
