version: '3.8'

services:
  backend:
    image: photos_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: /app/run.dev.sh
    ports:
      - 8000:8000
    volumes:
      - ./photos/:/app/photos/
      - static_volume:/app/static/
    depends_on:
      - database
      - redis

  frontend:
    image: photos_frontend
    build:
      context: .
      dockerfile: ./build/webpack/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./src/:/app/src/
      - ./node_modules/:/app/node_modules/
      - static_volume:/app/static/
    command: npx webpack --config webpack.dev.js

  redis:
    extends:
      file: docker-services.yml
      service: redis

  celery:
    extends:
      file: docker-services.yml
      service: celery
    build:
      target: development
    depends_on:
      - backend
      - database
      - redis

  database:
    extends:
      file: docker-services.yml
      service: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
