version: '3.8'

services:
  database:
    image: postgres:16.3-alpine
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
    environment:
      - POSTGRES_USER=photos
      - POSTGRES_PASSWORD=photos
      - POSTGRES_DB="gallery.doktortakes.photos"
