version: '3.8'

services:
  backend:
    image: photos_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./photos/:/app/photos/
      - static_volume:/app/static/
    depends_on:
      - database
    entrypoint: /app/run.dev.sh

  frontend:
    image: photos_frontend
    build:
      context: .
      dockerfile: ./build/webpack/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./src/:/app/src/
      - static_volume:/app/static/
    entrypoint: npx webpack --config webpack.dev.js

  database:
    extends:
      file: docker-services.yml
      service: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
