version: '3.8'

services:
  backend:
    image: photos_backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./photos/:/app/photos/
      - static_volume:/app/static/
    depends_on:
      - redis

  frontend:
    image: photos_frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ./build/webpack/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./src/:/app/src/
      - ./node_modules/:/app/node_modules/
      - static_volume:/app/static/
    command: npx webpack --config webpack.dev.js

  redis:
    extends:
      file: docker-services.yml
      service: redis

  celery:
    extends:
      file: docker-services.yml
      service: celery
    build:
      target: development
    depends_on:
      - backend
      - redis

volumes:
  static_volume:
