services:
  backend:
    image: photos-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-production
    env_file: .env.production
    ports:
      - 1337:1337
    entrypoint: /app/run.production.sh
