version: '3.8'

services:
  backend:
    image: photos_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: poetry run gunicorn photos.wsgi -c ./build/gunicorn.conf.py
    ports:
      - 1337:1337
