services:
  backend:
    image: photos-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-staging
    expose:
      - 1337
    depends_on:
      - database
    entrypoint: /app/run.dev.sh

  nginx:
    image: photos-nginx
    build: ./build/nginx/
    ports:
      - 443:443
    depends_on:
      - backend

  database:
    extends:
      file: docker-services.yml
      service: database
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
      - ./build/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data_staging:
  static_volume:
