version: '3.8'

services:
  backend:
    image: photos_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    command: /app/run.staging.sh
    expose:
      - 1337
    depends_on:
      - database
      - redis

  nginx:
    image: photos_nginx
    build: ./build/nginx/
    ports:
      - 443:443
    depends_on:
      - backend

  redis:
    extends:
      file: docker-services.yml
      service: redis

  celery:
    extends:
      file: docker-services.yml
      service: celery
    build:
      target: staging
    depends_on:
      - backend
      - database
      - redis
    command: /app/run-celery.staging.sh

  database:
    extends:
      file: docker-services.yml
      service: database
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/


volumes:
  postgres_data_staging:
  static_volume:
