# Generated by Django 5.0.6 on 2024-06-15 19:31

import django.core.validators
import django.db.models.deletion
import photos.fields
import photos.models.file
import photos.models.photo.thumbnail
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=photos.models.file.get_file_path)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('x_position', models.CharField(default='center', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('place', models.CharField(blank=True, help_text='The specific venue, building, or place', max_length=128)),
                ('location', models.CharField(blank=True, help_text='The city, state, and country', max_length=128)),
                ('timezone', models.CharField(default='US/Eastern', max_length=100)),
                ('description', models.CharField(blank=True, help_text='A brief description of this album', max_length=1000)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField(blank=True, editable=False, help_text='The path to this album; automatically set')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (10, 'Signed in'), (20, 'Owners'), (30, 'Staff'), (100, 'Superusers')], default=0)),
                ('access_code', models.CharField(blank=True, max_length=128)),
                ('groups', models.ManyToManyField(blank=True, related_name='albums', to='auth.group')),
                ('parent', models.ForeignKey(blank=True, help_text='The album that contains this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='photos.album')),
                ('users', models.ManyToManyField(blank=True, related_name='albums', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.license')),
            ],
            options={
                'get_latest_by': 'start',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(help_text='Original image with no modifications', upload_to=photos.models.photo.photo.get_original_path, verbose_name='Original image')),
                ('md5', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5')),
                ('original_filename', models.CharField(blank=True, max_length=1000)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=50)),
                ('taken', models.DateTimeField(editable=False)),
                ('edited', models.DateTimeField(editable=False)),
                ('exif', photos.fields.JSONField(blank=True, verbose_name='EXIF')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.album')),
            ],
            options={
                'ordering': ('taken', 'uploaded'),
                'get_latest_by': 'taken',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(blank=True, help_text='The cover photo for this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='albums', to='photos.tag'),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(help_text='Catalogue of Life identifier', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('rank', models.CharField(choices=[('domain', 'Domain'), ('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], default='species', max_length=50)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('parent_catalog_id', models.CharField(help_text='Catalogue of Life identifier', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='photos.taxon')),
            ],
            options={
                'verbose_name_plural': 'taxa',
            },
        ),
        migrations.CreateModel(
            name='PhotoTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.taxon')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='taxa',
            field=models.ManyToManyField(related_name='photos', through='photos.PhotoTaxon', to='photos.taxon'),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('display', 'Display'), ('square_xs', 'Square (extra small)'), ('square', 'Square (small)'), ('square_md', 'Square (medium)'), ('square_lg', 'Square (large)'), ('display_md', 'Regular (medium)'), ('cover', 'Cover')], max_length=10)),
                ('image', models.ImageField(blank=True, editable=False, height_field='height', null=True, upload_to=photos.models.photo.thumbnail.get_filename, width_field='width')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='photos.photo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('name',), name='unique_name_top_level'),
        ),
    ]
