# Generated by Django 2.2.7 on 2020-06-29 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import photos.fields
import photos.models.photo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('place', models.CharField(blank=True, help_text='The specific venue, building, or place', max_length=128)),
                ('location', models.CharField(blank=True, help_text='The city, state, and country', max_length=128)),
                ('timezone', models.CharField(default='US/Eastern', max_length=100)),
                ('description', models.CharField(blank=True, help_text='A brief description of this album', max_length=1000)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_size', models.CharField(choices=[('2400', '2400 x 1600'), ('3600', '3600 x 2400')], default='2400', max_length=4)),
                ('path', models.TextField(blank=True, editable=False, help_text='The path to this album; automatically set')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (10, 'Signed in'), (20, 'Owners'), (30, 'Staff'), (100, 'Superusers')], default=0)),
                ('access_code', models.CharField(blank=True, max_length=128)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'get_latest_by': 'start',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(help_text='Original image with no modifications', upload_to=photos.models.photo.get_original_path, verbose_name='Original image')),
                ('md5', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5')),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('sidecar_exists', models.BooleanField(default=False)),
                ('original_filename', models.CharField(blank=True, max_length=1000)),
                ('watermark', models.CharField(blank=True, choices=[('', 'None'), ('w', 'White'), ('b', 'Black')], default='w', max_length=1)),
                ('image', models.ImageField(blank=True, editable=False, help_text='Smaller image with watermark applied', null=True, upload_to=photos.models.photo.get_display_path, verbose_name='Display image')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=50)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=photos.models.photo.get_thumbnail_path)),
                ('square_thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=photos.models.photo.get_square_thumbnail_path)),
                ('taken', models.DateTimeField(editable=False)),
                ('edited', models.DateTimeField(editable=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('exif', photos.fields.JSONField(blank=True, verbose_name='EXIF')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Album')),
            ],
            options={
                'ordering': ('taken', 'uploaded'),
                'get_latest_by': 'taken',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(blank=True, help_text='The cover photo for this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='photos.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='albums', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The album that contains this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='photos.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='albums', to='photos.Tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'parent')},
        ),
    ]
