# Generated by Django 2.2.14 on 2020-07-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='local_path',
        ),
    ]
