# Generated by Django 2.2.14 on 2020-11-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_local_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(condition=models.Q(parent=None), fields=('name',), name='unique_name_top_level'),
        ),
    ]
