# Generated by Django 2.2.24 on 2021-11-13 06:31

from django.db import migrations, models
import photos.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201108_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=photos.models.file.get_file_path)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
