# Generated by Django 2.2.24 on 2021-11-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_herophoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
