# Generated by Django 2.2.24 on 2022-04-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_tagline'),
        ('photos', '0004_file'),
    ]

    operations = [
    ]
