# Generated by Django 2.2.24 on 2022-04-01 04:12

from django.db import migrations, models
import django.db.models.deletion
import photos.models.photo.thumbnail


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_merge_20220401_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('display', 'Display'), ('cover', 'Cover'), ('square', 'Square')], max_length=10)),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to=photos.models.photo.thumbnail.get_filename)),
                ('is_watermarked', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='photos.Photo')),
            ],
        ),
    ]
