# Generated by Django 2.2.24 on 2022-04-01 04:16

from django.db import migrations, transaction

from photos.models.photo.thumbnail import THUMBNAIL_COVER, THUMBNAIL_DISPLAY, THUMBNAIL_SMALL_SQUARE
from photos.utils.models import format_file_size


def combine_names(apps, schema_editor):
    Photo = apps.get_model('photos', 'Photo')
    Thumbnail = apps.get_model('photos', 'Thumbnail')

    with transaction.atomic():
        for photo in Photo.objects.all():
            images = (
                (photo.image, THUMBNAIL_DISPLAY),
                (photo.thumbnail, THUMBNAIL_COVER),
                (photo.square_thumbnail, THUMBNAIL_SMALL_SQUARE),
            )

            for image, type in images:
                if not image:
                    continue

                thumbnail = Thumbnail()

                thumbnail.photo = photo
                thumbnail.type = type

                thumbnail.image.name = image.name
                thumbnail.is_watermarked = False

                thumbnail.width = image.width
                thumbnail.height = image.height
                thumbnail.file_size = format_file_size(image.size)

                thumbnail.save()


class Migration(migrations.Migration):
    dependencies = [
        ('photos', '0007_thumbnail'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
