# Generated by Django 2.2.24 on 2022-04-01 17:52

from django.db import migrations, models
import photos.models.photo.watermark


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20220401_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=photos.models.photo.watermark.get_filename, width_field='width')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
