# Generated by Django 2.2.24 on 2022-04-01 23:29

from django.db import migrations, models
import photos.models.photo.thumbnail


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_watermark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(blank=True, editable=False, height_field='height', null=True, upload_to=photos.models.photo.thumbnail.get_filename, width_field='width'),
        ),
    ]
