# Generated by Django 3.2 on 2022-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20220401_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
