# Generated by Django 3.2 on 2022-04-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20220407_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='thumbnail_size',
            new_name='display_image_size',
        ),
    ]
