# Generated by Django 3.2 on 2022-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_rename_thumbnail_size_album_display_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='display_image_size',
            field=models.CharField(choices=[('2400', '2400 x 1600'), ('3000', '3000 x 2000'), ('3600', '3600 x 2400'), ('3840', '3840 x 2560'), ('4800', '4800 x 3200'), ('6000', '6000 x 4000')], default='3840', max_length=4),
        ),
    ]
