# Generated by Django 3.2 on 2022-04-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20220408_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='square_thumbnail',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
    ]
