# Generated by Django 3.2 on 2022-04-08 22:04

from django.db import migrations, models
import photos.models.photo.watermark


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20220408_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermark',
            name='height',
        ),
        migrations.RemoveField(
            model_name='watermark',
            name='width',
        ),
        migrations.AddField(
            model_name='watermark',
            name='apply_to_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watermark',
            name='image',
            field=models.ImageField(upload_to=photos.models.photo.watermark.get_filename),
        ),
        migrations.AddConstraint(
            model_name='watermark',
            constraint=models.UniqueConstraint(fields=('apply_to_size', 'color'), name='unique_size_color'),
        ),
    ]
