# Generated by Django 3.2 on 2022-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20220408_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='type',
            field=models.CharField(blank=True, choices=[('display', 'Display'), ('cover', 'Cover'), ('square', 'Square (small)'), ('square_lg', 'Square (large)')], max_length=10),
        ),
    ]
