# Generated by Django 3.2 on 2022-04-09 00:14

from django.db import migrations, transaction

from photos.tasks import update_large_square_thumbnail


def generate_large_square_thumbnails(apps, schema_editor):
    Album = apps.get_model('photos', 'Album')

    with transaction.atomic():
        for album in Album.objects.all().select_related('cover'):
            if not album.cover:
                continue

            update_large_square_thumbnail(album.cover, album.cover.original.file)
            album.save()


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_alter_thumbnail_type'),
    ]

    operations = [
        migrations.RunPython(generate_large_square_thumbnails),
    ]
