# Generated by Django 3.2 on 2022-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20220409_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='rating',
        ),
    ]
