# Generated by Django 3.2 on 2022-09-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_remove_photo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='display_image_size',
        ),
    ]
