# Generated by Django 3.2 on 2022-09-16 11:06

from django.db import migrations, transaction

from photos.models.photo.thumbnail import THUMBNAIL_COVER


def delete_cover_thumbnails(apps, schema_editor):
    Thumbnail = apps.get_model('photos', 'Thumbnail')

    with transaction.atomic():
        for thumbnail in Thumbnail.objects.filter(type=THUMBNAIL_COVER):
            thumbnail.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_remove_album_display_image_size'),
    ]

    operations = [
        migrations.RunPython(delete_cover_thumbnails),
    ]
