# Generated by Django 3.2 on 2023-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_auto_20230822_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='parent_catalog_id',
            field=models.CharField(default=None, help_text='Catalogue of Life identifier', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
