# Generated by Django 3.2 on 2023-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_auto_20230822_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='parent_catalog_id',
            field=models.CharField(help_text='Catalogue of Life identifier', max_length=10),
        ),
    ]
