# Generated by Django 3.2 on 2023-09-04 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0023_auto_20230901_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.taxon')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='taxa',
            field=models.ManyToManyField(related_name='photos', through='photos.PhotoTaxon', to='photos.Taxon'),
        ),
    ]
