# Generated by Django 3.2 on 2024-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0024_auto_20230904_0731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watermark',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='watermark',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='is_watermarked',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='type',
            field=models.CharField(blank=True, choices=[('display', 'Display'), ('square_xs', 'Square (extra small)'), ('square', 'Square (small)'), ('square_md', 'Square (medium)'), ('square_lg', 'Square (large)'), ('display_md', 'Regular (medium)'), ('cover', 'Cover')], max_length=10),
        ),
    ]
