# Generated by Django 3.2 on 2024-04-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0026_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.license'),
        ),
    ]
