# Generated by Django 3.2 on 2024-04-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0027_album_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='sidecar_exists',
        ),
    ]
