# Generated by Django 5.0.6 on 2024-06-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0028_remove_photo_sidecar_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='level',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='album',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The album that contains this album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='photos.album'),
        ),
    ]
