[django]
allowed_hosts = [
    "localhost",
    "127.0.0.1",
    "backend",
]
debug = true
use_local_storage = true

[database]
ENGINE = "django.db.backends.postgresql"
HOST = "database"
PORT = "5432"
NAME = "photos"
USER = "photos"
PASSWORD = "photos"
