# Generated by Django 5.0.6 on 2026-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('featured', 'Featured')], default='standard', max_length=16),
        ),
    ]
