# Generated by Django 5.0.6 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='placeholder_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
