# Generated by Django 6.0.3 on 2026-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exif',
            field=models.JSONField(blank=True, verbose_name='EXIF'),
        ),
    ]
