# Generated by Django 6.0.3 on 2026-03-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_exif'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='namespace',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
