# Generated by Django 6.0.3 on 2026-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_tag_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('featured', 'Featured'), ('external', 'External')], default='standard', max_length=16),
        ),
    ]
