# Generated by Django 6.0.3 on 2026-03-24 05:51

import photos.models.photo.thumbnail
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_creator_photo_description_photo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=photos.models.photo.thumbnail.get_filename),
        ),
    ]
