# Generated by Django 6.0.3 on 2026-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_code', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
