# Generated by Django 6.0.3 on 2026-03-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
