# Generated by Django 6.0.3 on 2026-03-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_alter_request_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagline',
        ),
    ]
