# Generated by Django 6.0.3 on 2026-03-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_request_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'taken', 'ordering': (models.OrderBy(models.F('order'), nulls_last=True), 'taken', 'uploaded')},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
